# brownie-config.yaml
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - hifi-finance/prb-math@2.4.1
  - BongaBeraCapital/bera-utils@0.0.1-alpha
  - BongaBeraCapital/bera-storage@0.0.0.5-dev

compiler:
  solc:
    version: 0.8.10
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@hifi-finance/prb-math=hifi-finance/prb-math@2.4.1'
      - '@bonga-bera-capital/bera-utils=BongaBeraCapital/bera-utils@0.0.1-alpha'
      - '@bonga-bera-capital/bera-storage=BongaBeraCapital/bera-storage@0.0.0.5-dev'

networks:
  default: development
  development:
    cmd: ganache-cli
    cmd_settings:
      port: 8545
      gas_limit: 6721975
      default_balance: 10000 ether
      accounts: 150
      evm_version: istanbul
      mnemonic: brownie
